package com.dannbrown.braziliandelight.compat.vanilla

import com.dannbrown.deltaboxlib.registry.datagen.DeltaboxCompostables
import com.dannbrown.braziliandelight.init.AddonBlocks
import com.dannbrown.braziliandelight.init.AddonItems

object AddonCompostables: DeltaboxCompostables(mutableMapOf(
    AddonBlocks.LEMON_LEAVES.asItem() to 0.3f,
    AddonBlocks.ACAI_PALM_LEAVES.asItem() to 0.3f,
    AddonBlocks.COCONUT_PALM_LEAVES.asItem() to 0.3f,
    AddonBlocks.COCONUT_PALM_SAPLING.asItem() to 0.3f,
    AddonBlocks.LEMON_SAPLING.asItem() to 0.3f,
    AddonBlocks.ACAI_PALM_SAPLING.asItem() to 0.3f,
    AddonBlocks.WILD_GARLIC.asItem() to 0.65f,
    AddonBlocks.WILD_CORN.asItem() to 0.65f,
    AddonBlocks.WILD_BEANS.asItem() to 0.65f,
    AddonBlocks.WILD_CASSAVA.asItem() to 0.65f,
    AddonBlocks.WILD_GUARANA.asItem() to 0.65f,
    AddonBlocks.WILD_COFFEE_BERRIES.asItem() to 0.65f,
    AddonBlocks.WILD_COLLARD_GREENS.asItem() to 0.65f,
    AddonBlocks.CARROT_CAKE.asItem() to 1f,
    AddonBlocks.CARROT_CAKE_WITH_CHOCOLATE.asItem() to 1f,
    AddonBlocks.PUDDING.asItem() to 1f,
    AddonBlocks.MINAS_CHEESE.asItem() to 1f,
    AddonBlocks.CHICKEN_POT_PIE.asItem() to 1f,
    AddonItems.CARROT_CAKE_SLICE.asItem() to 0.85f,
    AddonItems.CARROT_CAKE_WITH_CHOCOLATE_SLICE.asItem() to 0.85f,
    AddonItems.MINAS_CHEESE_SLICE.asItem() to 0.85f,
    AddonItems.PUDDING_SLICE.asItem() to 0.85f,
    AddonItems.CHICKEN_POT_PIE_SLICE.asItem() to 0.85f,
    AddonItems.LEMON.asItem() to 0.3f,
    AddonItems.LEMON_SLICE.asItem() to 0.3f,
    AddonItems.YERBA_MATE_LEAVES.asItem() to 0.3f,
    AddonItems.DRIED_YERBA_MATE.asItem() to 0.3f,
    AddonItems.GUARANA_FRUIT.asItem() to 0.3f,
    AddonItems.COFFEE_BERRIES.asItem() to 0.3f,
    AddonItems.COLLARD_GREENS.asItem() to 0.65f,
    AddonItems.GARLIC_BULB.asItem() to 0.65f,
    AddonItems.COCONUT_SLICE.asItem() to 0.3f,
    AddonItems.CORN.asItem() to 0.3f,
    AddonItems.COOKED_CORN.asItem() to 0.65f,
    AddonItems.ROASTED_GARLIC.asItem() to 0.65f,
    AddonItems.CORN_FLOUR.asItem() to 0.3f,
    AddonItems.CASSAVA_FLOUR.asItem() to 0.3f,
    AddonItems.BEAN_POD.asItem() to 0.3f,
    AddonBlocks.BUDDING_CASSAVA.asItem() to 0.65f,
    AddonBlocks.BUDDING_COFFEE.asItem() to 0.3f,
    AddonBlocks.BUDDING_BEANS_CROP.asItem() to 0.3f,
    AddonBlocks.BUDDING_CORN.asItem() to 0.3f,
    AddonBlocks.CARIOCA_BEANS_CROP.asItem() to 0.3f,
    AddonBlocks.BUDDING_ACAI_BRANCH.asItem() to 0.3f,
    AddonBlocks.BUDDING_GUARANA.asItem() to 0.3f,
    AddonBlocks.WHITE_KERNELS_CROP.asItem() to 0.3f,
    AddonBlocks.COCONUT.asItem() to 0.3f,
    AddonBlocks.GREEN_COCONUT.asItem() to 0.3f,
    AddonBlocks.SPARSE_DRY_GRASS.asItem() to 0.3f,
    AddonBlocks.TALL_SPARSE_DRY_GRASS.asItem() to 0.3f,
    AddonBlocks.YERBA_MATE_BUSH.asItem() to 0.3f,
))


