package com.dannbrown.braziliandelight.lib

object AddonNames {
  val BRAZIL_FLAG = "brazil_flag"

  val BEAN = "bean"
  val BEAN_POD = "bean_pod"
  val BLACK_BEANS = "black_beans"
  val CARIOCA_BEANS = "carioca_beans"
  val GARLIC = "garlic"
  val GARLIC_BULB = "garlic_bulb"
  val ACAI_BERRIES = "acai_berries"
  val GUARANA_FRUIT = "guarana_fruit"
  val GUARANA_SEEDS = "guarana_seeds"
  val GREEN_COCONUT = "green_coconut"
  val COCONUT = "coconut"
  val CORN = "corn"
  val CASSAVA = "cassava"
  val COLLARD_GREENS = "collard_greens"
  val COLLARD_GREENS_SEED = "collard_greens_seed"
  val COFFEE_BERRIES = "coffee_berries"
  val COFFEE_BEANS = "coffee_beans"
  val COFFEE_SEEDS = "coffee_seeds"
  val KERNELS = "kernels"
  val WHITE_KERNELS = "white_kernels"
  val GUARANA_POWDER = "guarana_powder"
  val CASSAVA_FLOUR = "cassava_flour"
  val CORN_FLOUR = "corn_flour"
  val LEMON = "lemon"
  val LEMON_SLICE = "lemon_slice"
  val SALT = "salt"
  val SALT_BUCKET = "salt_bucket"
  val GARLIC_CLOVE = "garlic_clove"
  val COCONUT_SLICE = "coconut_slice"
  val COOKED_CORN = "cooked_corn"
  val CASSAVA_ROOT = "cassava_root"
  val BUTTER = "butter"
  val HEAVY_CREAM_BUCKET = "heavy_cream_bucket"
  val CONDENSED_MILK = "condensed_milk"

  val CARROT_CAKE = "carrot_cake"
  val CARROT_CAKE_WITH_CHOCOLATE = "carrot_cake_with_chocolate"
  val MINAS_CHEESE = "minas_cheese"
  val CHICKEN_POT_PIE = "chicken_pot_pie"
  val PUDDING = "pudding"
  val SALPICAO = "salpicao"
  val CUZCUZ_PAULISTA = "cuzcuz_paulista"
  val FEIJOADA_POT = "feijoada_pot"
  val GREEN_SOUP_POT = "green_soup_pot"
  val FISH_MOQUECA_POT = "fish_moqueca_pot"
  val STROGANOFF_POT = "stroganoff_pot"

  val MINAS_CHEESE_SLICE = "minas_cheese_slice"
  val MINAS_CHEESE_ON_A_STICK = "minas_cheese_on_a_stick"
  val GRILLED_CHEESE_ON_A_STICK = "grilled_cheese_on_a_stick"
  val CARROT_CAKE_SLICE = "carrot_cake_slice"
  val CARROT_CAKE_WITH_CHOCOLATE_SLICE = "carrot_cake_with_chocolate_slice"
  val CHICKEN_POT_PIE_SLICE = "chicken_pot_pie_slice"
  val PUDDING_SLICE = "pudding_slice"
  val PASTEL_DOUGH = "pastel_dough"

  val SHRIMP = "shrimp"
  val COOKED_SHRIMP = "cooked_shrimp"

  val TUCUPI = "tucupi"
  val RAW_PASTEL = "raw_pastel"
  val PASTEL = "pastel"
  val FRIED_CASSAVA_WITH_BUTTER = "fried_cassava_with_butter"
  val RAW_COXINHA = "raw_coxinha"
  val COXINHA = "coxinha"
  val RAW_CASSAVA_FRITTERS = "raw_cassava_fritters"
  val CASSAVA_FRITTERS = "cassava_fritters"
  val ROASTED_GARLIC = "roasted_garlic"
  val COCONUT_DRINK = "coconut_drink"
  val COCONUT_MILK = "coconut_milk"
  val GUARANA_SODA = "guarana_soda"
  val ACAI_CREAM = "acai_cream"
  val BRIGADEIRO_CREAM = "brigadeiro_cream"
  val SWEET_LOVE_APPLE = "sweet_love_apple"
  val GARAPA = "garapa"
  val GUARANA_JUICE = "guarana_juice"
  val BROA = "broa"
  val CUZCUZ = "cuzcuz"

  val ANGU = "angu"
  val POPCORN = "popcorn"
  val CHEESE_BREAD_DOUGH = "cheese_bread_dough"
  val CHEESE_BREAD = "cheese_bread"
  val BRAZILIAN_BREAKFAST = "brazilian_breakfast"
  val BRAZILIAN_DINNER = "brazilian_dinner"
  val BRAZILIAN_RICE = "brazilian_rice"
  val BREAD_WITH_BUTTER = "bread_with_butter"
  val GARLIC_BREAD = "garlic_bread"
  val CHICKEN_SAUCE = "chicken_sauce"
  val TROPEIRO_BEANS = "tropeiro_beans"
  val COOKED_BEANS = "cooked_beans"
  val COLLARD_GREENS_FAROFA = "collard_greens_farofa"
  val COLLARD_GREENS_SALAD = "collard_greens_salad"
  val PLATE_OF_STROGANOFF = "plate_of_stroganoff"
  val PLATE_OF_GREEN_SOUP = "plate_of_green_soup"
  val PLATE_OF_FISH_MOQUECA = "plate_of_fish_moqueca"
  val PLATE_OF_FEIJOADA = "plate_of_feijoada"
  val FRIED_FISH_WITH_ACAI = "fried_fish_with_acai"
  val PLATE_OF_FRIED_FISH_WITH_ACAI = "plate_of_fried_fish_with_acai"
  val PLATE_OF_SALPICAO = "plate_of_salpicao"
  val PLATE_OF_CUZCUZ_PAULISTA = "plate_of_cuzcuz_paulista"

  val SWEET_LOVE_APPLE_TRAY = "sweet_love_apple_tray"

  val CHIMARRAO = "chimarrao"
  val YERBA_MATE_LEAVES = "yerba_mate_leaves"
  val DRIED_YERBA_MATE = "dried_yerba_mate"
}